# Generated by Django 4.2 on 2023-04-13 22:50

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.user_directory_path_img, verbose_name='product image'),
        ),
    ]
